name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t BMI .
    - name: Run BMI
      run: docker run BMI

      # Notify on failures
    - name: Notify on failures
      if: ${{ failure() }}
      run: echo "There were some errors or issues in the CI process."

      # Notify on success
    - name: Notify on success
      if: ${{ success() }}
      run: echo "CI process completed successfully."
